version: '2'

services:
  tzg_hastebin:
    restart: always
    image: docker.thezengarden.net/hastebin
    build: .
    command: npm start
    ports:
      - '7777:7777'
    volumes:
      - ./etc/config.js:/haste-server/config.js
    depends_on:
      - tzg_redis

  tzg_redis:
    restart: always
    image: redis:4.0.2-alpine
    expose:
      - 6379
    volumes:
      - ./etc/redis.conf:/etc/redis.conf
