version: '2'

services:
  tzg_hastebin:
    container_name: tzg_hastebin
    restart: always
    image: thezengarden/hastebin
    build: .
    command: npm start
    networks:
      - tzg_hastebin
    ports:
      - '7777:7777'
    volumes:
      - ./etc/config.js:/haste-server/config.js
    depends_on:
      - tzg_redis

  tzg_redis:
    container_name: tzg_redis
    restart: always
    image: redis:4-alpine
    networks:
      - tzg_hastebin
    expose:
      - 6379
    volumes:
      - ./etc/redis.conf:/etc/redis.conf

networks:
  tzg_hastebin:
